---
core:
  num_workers: 100

inventory:
  plugin: nornir.plugins.inventory.netbox.NBInventory
  options:
    nb_url: 'http://192.168.122.1:8000'
    nb_token: '0123456789abcdef0123456789abcdef01234567'
    ssl_verify: False
  transform_function: "scriptsote.helpers.adapt_user_password"
  

